### ISSUE TITLE
Missing TypeScript type definitions + repo out of date

### ISSUE THREAD

**Issue by elektronik2k5** [brainhubeu/react-permissible#10]
Hello and thanks for creating this package!

I intend to use it in a TypeScript project and wrote the missing types. I'd like to contribute them, but it seems like the repo is out of date.
Last commit to this repo is from June 28th, while v1.5.0 was published to npm in September.

The fact that the repo isn't up to date with the published package also reduces credibility - since without diving into published sources, there's no easy way to inspect the source code.

@kkoscielniak @piotr-s-brainhub @adam-golab

**Comment by kkoscielniak** [comment]
Hello @elektronik2k5! 

We'll take a look at this one and check why there is a mismatch between GitHub and nom registry.

**Comment by piotr-s-brainhub** [comment]
@elektronik2k5 

thanks for your interest in this library!
we've had failing tests and lint since some time so that's the reason it was not published but recently I was working on automatic publishing in CircleCI so I needed to publish in order to test this process - sorry for not unpublishing this, now it's too late as NPM allows for unpublishing only within 24 hours;

however we're working on fixing tests and lint so the build will be succeeding and thanks to automatic publishing, there will be no mismatch between GitHub and NPM

**Comment by kkoscielniak** [comment]
Hello @elektronik2k5,

We've fixed tests and linter issues and build passes. Both repository and npm registry are up to date. 

You're more than welcome to add missing types 🙂

**Comment by kkoscielniak** [comment]
@elektronik2k5 

We will close this issue, but feel free to open a PR whenever you'd like.
